### DATA IMPORTING

In [82]:
import pandas as pd

In [83]:
df = pd.read_csv(r'C:\Users\jasee\Downloads\project 4.1\data\samplesuperstore.csv')

### DATA INSPECTION

In [84]:
print(df.shape)

(10194, 24)

In [85]:
print(df.dtypes)

row_id               int64
order_id               str
order_date             str
ship_date              str
ship_mode              str
customer_id            str
customer_name          str
segment                str
Country/Region         str
city                   str
State/Province         str
postal_code            str
region                 str
product_id             str
category               str
sub_category           str
product_name           str
sales              float64
quantity             int64
discount           float64
profit             float64
shipping days          str
profit margin %    float64
order year           int64
dtype: object

In [86]:
print(df.isnull().sum())

row_id             0
order_id           0
order_date         0
ship_date          0
ship_mode          0
customer_id        0
customer_name      0
segment            0
Country/Region     0
city               0
State/Province     0
postal_code        0
region             0
product_id         0
category           0
sub_category       0
product_name       0
sales              0
quantity           0
discount           0
profit             0
shipping days      0
profit margin %    0
order year         0
dtype: int64

In [87]:
print(df[["sales", "quantity","discount","profit"]].describe())

              sales      quantity      discount        profit
count  10194.000000  10194.000000  10194.000000  10194.000000
mean     228.225854      3.791838      0.155385     28.673417
std      619.906839      2.228317      0.206249    232.465115
min        0.444000      1.000000      0.000000  -6599.978000
25%       17.220000      2.000000      0.000000      1.760800
50%       53.910000      3.000000      0.200000      8.690000
75%      209.500000      5.000000      0.200000     29.297925
max    22638.480000     14.000000      0.800000   8399.976000

In [88]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [89]:
dupes = df[df.duplicated(subset=["order_id"], keep=False)]
print(dupes.shape)
dupes.head()

(7601, 24)

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,Country/Region,city,...,category,sub_category,product_name,sales,quantity,discount,profit,shipping days,profit margin %,order year
1,2,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-5.4870,4 days,-155.00,2023
2,3,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,Office Supplies,Labels,Avery 508,11.784,3,0.2,4.2717,4 days,36.25,2023
3,4,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,Office Supplies,Storage,SAFCO Boltless Steel Shelving,272.736,3,0.2,-64.7748,4 days,-23.75,2023
5,6,US-2023-167199,2023-01-06,2023-01-10,Standard Class,ME-17320,Maria Etezadi,Home Office,United States,Henderson,...,Furniture,Chairs,Global Deluxe High-Back Manager's Chair,2573.820,9,0.0,746.4078,4 days,29.00,2023
6,7,US-2023-167199,2023-01-06,2023-01-10,Standard Class,ME-17320,Maria Etezadi,Home Office,United States,Henderson,...,Office Supplies,Art,Rogers Handheld Barrel Pencil Sharpener,5.480,2,0.0,1.4796,4 days,27.00,2023

### DATA CLEANING

In [90]:
df['order_date'] = pd.to_datetime(df['order_date'])
df['ship_date'] = pd.to_datetime(df['ship_date'])

In [91]:
df.dtypes

row_id                      int64
order_id                      str
order_date         datetime64[us]
ship_date          datetime64[us]
ship_mode                     str
customer_id                   str
customer_name                 str
segment                       str
Country/Region                str
city                          str
State/Province                str
postal_code                   str
region                        str
product_id                    str
category                      str
sub_category                  str
product_name                  str
sales                     float64
quantity                    int64
discount                  float64
profit                    float64
shipping days                 str
profit margin %           float64
order year                  int64
dtype: object

In [92]:
df['shipping days'] = (df['ship_date'] - df['order_date'])
df.head()

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,Country/Region,city,...,category,sub_category,product_name,sales,quantity,discount,profit,shipping days,profit margin %,order year
0,1,US-2023-103800,2023-01-03,2023-01-07,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,...,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448,2,0.2,5.5512,4 days,33.75,2023
1,2,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-5.4870,4 days,-155.00,2023
2,3,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,Office Supplies,Labels,Avery 508,11.784,3,0.2,4.2717,4 days,36.25,2023
3,4,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,Office Supplies,Storage,SAFCO Boltless Steel Shelving,272.736,3,0.2,-64.7748,4 days,-23.75,2023
4,5,US-2023-141817,2023-01-05,2023-01-12,Standard Class,MB-18085,Mick Brown,Consumer,United States,Philadelphia,...,Office Supplies,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.536,3,0.2,4.8840,7 days,25.00,2023

In [93]:
df['shipping days'] = (df['ship_date'] - df['order_date'])
print(df.groupby('region')['shipping days'].mean().round(1))

region
Central   4 days 01:17:05.267665
East      3 days 21:55:05.827193
South            3 days 23:01:20
West      3 days 22:34:07.340916
Name: shipping days, dtype: timedelta64[us]

C:\Users\jasee\AppData\Local\Temp\ipykernel_29268\2114188166.py:2: UserWarning: obj.round has no effect with datetime, timedelta, or period dtypes. Use obj.dt.round(...) instead.
  print(df.groupby('region')['shipping days'].mean().round(1))

In [94]:
df["profit margin %"] = ((df["profit"] / df["sales"]) * 100).round(2)
df.head()

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,Country/Region,city,...,category,sub_category,product_name,sales,quantity,discount,profit,shipping days,profit margin %,order year
0,1,US-2023-103800,2023-01-03,2023-01-07,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,...,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448,2,0.2,5.5512,4 days,33.75,2023
1,2,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-5.4870,4 days,-155.00,2023
2,3,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,Office Supplies,Labels,Avery 508,11.784,3,0.2,4.2717,4 days,36.25,2023
3,4,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,Office Supplies,Storage,SAFCO Boltless Steel Shelving,272.736,3,0.2,-64.7748,4 days,-23.75,2023
4,5,US-2023-141817,2023-01-05,2023-01-12,Standard Class,MB-18085,Mick Brown,Consumer,United States,Philadelphia,...,Office Supplies,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.536,3,0.2,4.8840,7 days,25.00,2023

In [95]:
print(df.groupby("sub_category")["profit margin %"].mean().sort_values(ascending=False).head().round(1))

sub_category
Paper        42.5
Labels       42.5
Envelopes    42.3
Copiers      32.0
Fasteners    30.6
Name: profit margin %, dtype: float64

In [96]:
df["order year"] = df["order_date"].dt.year

In [97]:
df.rename(columns={"Row ID": "row_id","Order ID": "order_id","Order Date": "order_date","Ship Date": "ship_date","Ship Mode": "ship_mode","Customer ID": "customer_id","Customer Name": "customer_name","Segment": "segment","Country": "country","City": "city","State": "state","Postal Code": "postal_code","Region": "region","Product ID": "product_id","Category": "category","Sub-Category": "sub_category","Product Name": "product_name","Sales": "sales","Quantity": "quantity","Discount": "discount","Profit": "profit"}, inplace=True)

In [98]:
df.head(3)

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,Country/Region,city,...,category,sub_category,product_name,sales,quantity,discount,profit,shipping days,profit margin %,order year
0,1,US-2023-103800,2023-01-03,2023-01-07,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,...,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448,2,0.2,5.5512,4 days,33.75,2023
1,2,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-5.4870,4 days,-155.00,2023
2,3,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,Office Supplies,Labels,Avery 508,11.784,3,0.2,4.2717,4 days,36.25,2023

### DATA EXPORTING

In [100]:
df.to_csv('C:\\Users\\jasee\\Downloads\\project 4.1\\output\\superstore_cleaned.csv', index=False)